name: CustomMOTD
version: '${version}'
main: wtf.wooly.custommotd.CustomMotd
api-version: '26.1.2'
authors: [Woolyenough]
website: https://modrinth.com/project/custom-motd

permissions:
  custommotd.admin:
    description: Grants access to CustomMOTD admin commands
    default: op