name: CustomMotd
version: '${version}'
main: wtf.wooly.custommotd.CustomMotd
api-version: '1.21'
authors: [Woolyenough]
website: https://modrinth.com/project/custom-motd

commands:
  motd-reload:
    description: Reloads config and icon
    permission: custommotd.admin
  max-players:
    aliases:
      - set-max-players
    description: Manually set max player limit for the server
    permission: custommotd.admin